wandb_version: 1

learning_rate:
  desc: null
  value: adaptive
learning_rate_init:
  desc: null
  value: 0.01
alpha:
  desc: null
  value: 0.1
hidden_layer_sizes:
  desc: null
  value:
  - 30
  - 30
  - 30
max_iter:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.17.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724411833
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.12.0
      5: 0.17.7
      8:
      - 4
      - 5
      13: darwin-arm64
